export const REQUEST_USER_REGISTRATION = 'REQUEST_USER_REGISTRATION';
export const SUCCESS_USER_REGISTRATION = 'SUCCESS_USER_REGISTRATION';
export const FAILED_USER_REGISTRATION = 'FAILED_USER_REGISTRATION';
export const REQUEST_USER_EMAIL_OTP = 'REQUEST_USER_EMAIL_OTP';
export const SUCCESS_USER_EMAIL_OTP = 'SUCCESS_USER_EMAIL_OTP';
export const FAILED_USER_EMAIL_OTP = 'FAILED_USER_EMAIL_OTP';
export const REQUEST_OTP_VERIFICATION = 'REQUEST_OTP_VERIFICATION';
