import {Dimensions, StyleSheet} from 'react-native';
import {COLORS} from '../../assets/Theme/colors';
const windowWidth = Dimensions.get('window').width;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.white,
  },
  inner_container: {
    height: 100,
    width: '100%',
    backgroundColor: COLORS.primary,
    borderBottomRightRadius: 20,
    borderBottomLeftRadius: 20,
    position: 'absolute',
    top: 50,
  },
  card_view: {
    width: '80%',
    backgroundColor: COLORS.white,
    elevation: 5,
    alignSelf: 'center',
    borderRadius: 10,
    marginTop: 20,
    overflow: 'hidden',
  },
  like_view: {
    height: 40,
    width: 40,
    borderRadius: 20,
    alignSelf: 'flex-end',
    backgroundColor: COLORS.coupon_code_bg_color,
    justifyContent: 'center',
    alignItems: 'center',
    top: -4,
    left: 4,
  },
  logo_view: {
    height: 60,
    width: 140,
    backgroundColor: COLORS.white,
    elevation: 5,
    alignSelf: 'center',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  logo: {
    height: 40,
    width: 100,
    resizeMode: 'contain',
  },
  cash_back_str: {
    alignSelf: 'center',
    marginVertical: 10,
  },
  cash_back_text: {
    fontSize: 12,
    fontWeight: '500',
  },
  shopnow_btn: {
    backgroundColor: COLORS.primary,
    width: windowWidth - 200,
    borderRadius: 20,
    alignSelf: 'center',
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 15,
  },
  btn_text: {
    color: COLORS.white,
    textAlign: 'center',
    width: '100%',
    fontSize: 15,
    fontWeight: '400',
  },
  card_bottom_view: {
    justifyContent: 'space-between',
    flexDirection: 'row',
    marginHorizontal: 15,
    marginVertical: 10,
  },
  card_bottom_text: {
    fontSize: 14,
    color: COLORS.grey,
    fontWeight: '400',
  },
  hiw_modal_title: {
    fontSize: 24,
    color: COLORS.black,
    fontWeight: 'bold',
    marginLeft: 10,
    marginBottom: 20,
  },
  hiw_row: {
    flexDirection: 'row',
    paddingBottom: 8,
    marginBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border_light,
  },

  hiw_num: {
    fontWeight: '600',
    color: COLORS.secondary,
    marginRight: 10,
    fontSize: 30,
  },

  hiw_title: {
    fontSize: 16,
    fontWeight: '700',
    color: COLORS.black,
  },
  hiw_desc: {
    fontSize: 14,
    flexWrap: 'wrap',
    flex: 8,
    width: 320,
    marginTop: 5,
  },
  terms_content: {
    marginHorizontal: 10,
  },
  data_container: {
    marginHorizontal: 15,
  },
  tr_main_view: {
    width: '100%',
    padding: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  tr_view: {
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
    paddingVertical: 10,
  },
  verticalSeparator: {
    height: '100%',
    alignSelf: 'center',
    width: 1,
    backgroundColor: COLORS.grey_underline,
  },
  tr_title: {
    color: COLORS.grey,
    fontSize: 12,
    fontWeight: '400',
  },
  tr_desc: {
    color: COLORS.black,
    fontSize: 14,
    fontWeight: 'bold',
  },
  cr_title: {
    fontSize: 14,
    fontWeight: 'bold',
    marginTop: 20,
    marginBottom: 15,
    textTransform: 'capitalize',
    color: COLORS.blackText,
  },
  cb_card: {
    backgroundColor: COLORS.white,
    paddingTop: 10,
    borderRadius: 5,
    shadowOpacity: 1,
    elevation: 4,
  },
  cb_modal_content: {
    height: 300,
    marginBottom: 10,
    width: windowWidth - 40,
    alignSelf: 'center',
  },
  cb_row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 10,
    paddingBottom: 5,
    marginBottom: 5,
    borderBottomWidth: 0.5,
    borderBottomColor: COLORS.border_light,
  },
  cb_text: {
    fontSize: 12,
    color: COLORS.secondary,
  },
  cb_rate_title: {
    fontSize: 12,
    width: '60%',
    color: COLORS.blackText,
    marginVertical: 3,
  },
  down_arrow: {
    marginLeft: 5,
  },
  view_more_btn: {
    height: 35,
    width: '100%',
    alignSelf: 'center',
  },
  view_more_cb: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.cb_rates,
    borderBottomRightRadius: 5,
    height: 35,
    width: '100%',
    borderBottomLeftRadius: 5,
  },
  view_more_text: {
    fontSize: 12,
    color: COLORS.blackText,
  },
  co_title: {
    fontSize: 12,
    fontWeight: '600',
    marginTop: 20,
    marginBottom: 10,
    textTransform: 'capitalize',
  },
  empty_cp_view: {
    alignSelf: 'center',
  },
  empty_coupon_list: {
    fontSize: 16,
    color: COLORS.blackText,
    fontWeight: 'bold',
    marginVertical: 20,
  },
  co_title: {
    fontSize: 12,
    color: COLORS.blackText,
    marginTop: 20,
    fontWeight: '600',
  },
  list: {
    width: windowWidth,
    alignSelf: 'center',
  },
  row: {
    justifyContent: 'space-around',
    flex: 1,
  },
  cpn: {
    width: windowWidth / 2.5,
  },
  main_footer_title: {
    fontSize: 16,
  },
  footer_image: {
    height: 100,
    width: 100,
    resizeMode: 'contain',
  },
  cr_modal_title: {
    fontSize: 18,
    color: COLORS.black,
    fontWeight: 'bold',
    marginLeft: 10,
    marginBottom: 20,
  },
});
